import json
import random

MOCK_COINS = [
    {
        "country": "United States",
        "denomination": "Quarter Dollar",
        "year": "1965",
        "mint_mark": None,
        "estimated_grade": "VF-30",
        "mint_errors": [],
        "varieties": None,
        "error_premium": False,
        "special_notes": "Mock server response — OpenAI key is not configured.",
        "identifiable": True,
        "confidence": 84,
        "alternatives": [
            {"coin": "Washington Quarter", "confidence": 72},
            {"coin": "Roosevelt Dime", "confidence": 41},
            {"coin": "Kennedy Half Dollar", "confidence": 32},
        ],
    },
    {
        "country": "United States",
        "denomination": "One Cent",
        "year": "1982",
        "mint_mark": None,
        "estimated_grade": "XF-40",
        "mint_errors": [],
        "varieties": "Large Date / Small Date variety possible",
        "error_premium": False,
        "special_notes": "Mock server response — OpenAI key is not configured.",
        "identifiable": True,
        "confidence": 78,
        "alternatives": [
            {"coin": "Lincoln Memorial Cent", "confidence": 69},
            {"coin": "Wheat Cent", "confidence": 28},
            {"coin": "Jefferson Nickel", "confidence": 18},
        ],
    },
    {
        "country": "Canada",
        "denomination": "Silver Dollar",
        "year": "1948",
        "mint_mark": None,
        "estimated_grade": "AU-55",
        "mint_errors": [],
        "varieties": None,
        "error_premium": False,
        "special_notes": "Mock server response — OpenAI key is not configured.",
        "identifiable": True,
        "confidence": 71,
        "alternatives": [
            {"coin": "1947 Canadian Silver Dollar", "confidence": 44},
        ],
    },
]


def _flatten_text(messages):
    parts = []
    for message in messages or []:
        content = message.get("content")
        if isinstance(content, str):
            parts.append(content)
        elif isinstance(content, list):
            for item in content:
                if isinstance(item, dict) and item.get("type") == "text":
                    parts.append(item.get("text", ""))
    return "\n".join(parts)


def _has_image(messages):
    for message in messages or []:
        content = message.get("content")
        if isinstance(content, list):
            for item in content:
                if isinstance(item, dict) and item.get("type") == "image_url":
                    return True
    return False


def build_mock_reply(payload):
    """Return plausible fake OpenAI reply text based on which of the app's known
    prompts this call matches, so a scan can complete end-to-end without a
    working OpenAI key."""
    messages = payload.get("messages", [])
    text = _flatten_text(messages)

    if _has_image(messages):
        coin = random.choice(MOCK_COINS)
        return (
            f"Obverse shows a portrait consistent with a {coin['year']} {coin['country']} "
            f"{coin['denomination']}. Reverse design and inscriptions match the expected type. "
            f"Metal color and wear are consistent with an estimated grade of {coin['estimated_grade']}. "
            "No doubling, off-center strike, or die cracks observed. "
            "(Mock description — server MOCK_MODE is on because no working OpenAI key is configured.)"
        )

    if "unidentifiable_reason" in text and "alternatives" in text:
        return json.dumps(random.choice(MOCK_COINS))

    if "condition_assumed" in text and "error_value_note" in text:
        return json.dumps({
            "low": round(random.uniform(0.25, 5), 2),
            "high": round(random.uniform(5, 50), 2),
            "condition_assumed": "VF-30",
            "error_value_note": None,
            "reasoning": "Mock value estimate — server MOCK_MODE is on because no working OpenAI key is configured.",
        })

    if "3 exciting sentences" in text:
        return (
            "This coin has a story worth telling! Its design and wear tell us a lot about its "
            "circulation history. (Mock summary — server MOCK_MODE is on because no working OpenAI key is configured.)"
        )

    if "item_specifics" in text:
        return json.dumps({
            "title": "Mock Listing — configure a real OpenAI key to generate this for real",
            "subtitle": "Server is running in MOCK_MODE",
            "description": "This is placeholder eBay listing copy generated by the Flask mock responder because no working OpenAI key is configured.",
            "item_specifics": [{"label": "Mode", "value": "Mock"}],
            "shipping_notes": "N/A — mock data",
        })

    return "Mock response — server MOCK_MODE is on because no working OpenAI key is configured."
